#!/usr/bin/env node
require('@babel/register', {
  cache: true,
});

require('./conf')();
const conf = require('nconf');

const server = require('./server').default;
const { serverLogger: logger } = require('./server/lib/logger');

server.set('port', conf.get('PORT') || 8080);

server.listen(server.get('port'), () => {
  logger.info(`Server listening on port ${server.get('port')}`);
});
